data:
  gpu: 0
  num_workers: 10
  in_memory: 1
logging:
  folder: /tmp/
model:
  arch: 'resnet18'
resolution:
  end_ramp: 0
  min_res: 160
  max_res: 160
lr:
  lr_schedule_type: 'cyclic'
  lr_peak_epoch: 2
training:
  bn_wd: 0
  epochs: 90
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  distributed: 0
validation:
  lr_tta: true
  resolution: 224
dist:
  world_size: 1