model:
  antialias: false
  arch: 'resnet50'
resolution:
  min_res: 160
  max_res: 160
  end_ramp: 0
data:
  gpu: 0
  train_dataset: '/mnt/cfs/home/engstrom/store/ffcv/train_500_0.5_90.ffcv'
  val_dataset: '/mnt/cfs/home/engstrom/store/ffcv/val_500_0.5_90.ffcv'
  num_workers: 10
logging:
  folder: '/tmp/'
training:
  batch_size: 64
  optimizer: "sgd"
  bn_momentum: 0
  lr: 0.275
  momentum: 0.9
  weight_decay: 1e-4
  epochs: 90
  label_smoothing: 0.1
  lr_schedule_type: 'step'
  step_ratio: 0.1
  step_length: 20
  mixup_alpha: 0.2
  distributed: 1
validation:
  batch_size: 512
  resolution: 224
  lr_tta: True
dist:
  world_size: 8
