data:
  in_memory: 1
  num_workers: 12
  train_dataset: /home/ubuntu/train_500_0.5_90.ffcv
  val_dataset: /home/ubuntu/val_500_0.5_90.ffcv
dist:
  world_size: 8
logging:
  folder: /home/ubuntu/store/ffcv_rn50_8gpu/3872322e-0a9f-4102-a05a-803f0fea30e1
lr:
  lr: 1.7
  lr_schedule_type: cyclic
model:
  arch: resnet50
resolution:
  end_ramp: 48
  max_res: 192
  min_res: 160
  start_ramp: 41
training:
  batch_size: 512
  bn_wd: 0
  distributed: 1
  epochs: 56
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
uid: a2e443e4-0a42-49b5-a1f4-18f19689b2b1
validation:
  lr_tta: true
  resolution: 256
