# This is a basic workflow to help you get started with Actions

name: Push Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ new_ver ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build and upload the docs
        run: |
          conda create -n ffcv python=3.9 pkg-config compilers libjpeg-turbo opencv pytorch torchvision cudatoolkit=11.3 numba -c pytorch -c conda-forge
          conda activate ffcv
          cd docs
          pip install -U ../
          make html
          git branch -D ghpages || echo "branch exists"
          git checkout -B ghpages
          cd ..
          git config --global user.email "ailyas@mit.edu"
          git config --global user.name "Andrew Ilyas"
          git add --force docs
          git commit -m generate docs
          git push --force -u origin ghpages
